// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW14W0_bQlJrswH-tOvEchdCJ3iLPXyI',
    appId: '1:798228435749:android:56b99e61672351647a40cc',
    messagingSenderId: '798228435749',
    projectId: 'chatapp-f2600',
    storageBucket: 'chatapp-f2600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_NH3n_DTzQ65w4PH8TWAWo66-vn0OzE',
    appId: '1:798228435749:ios:4431b0bb0e97001f7a40cc',
    messagingSenderId: '798228435749',
    projectId: 'chatapp-f2600',
    storageBucket: 'chatapp-f2600.appspot.com',
    androidClientId: '798228435749-f9v4e9crc2iv71olhj4c6kfopa35q0ou.apps.googleusercontent.com',
    iosClientId: '798228435749-tndnlfogfh83l0cb9u8nq6ad7l413hfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatuiapp',
  );

}